# Generated by Django 2.2.4 on 2019-08-12 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takalapp', '0002_profile_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='token',
            field=models.CharField(max_length=246, unique=True),
        ),
    ]
