# Generated by Django 2.2.4 on 2019-08-12 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('takalapp', '0003_auto_20190812_1030'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=200)),
                ('startpoint_lat', models.CharField(max_length=200)),
                ('startpoint_lng', models.CharField(max_length=200)),
                ('passeddistance', models.CharField(max_length=200)),
                ('burenedcalory', models.CharField(max_length=200)),
                ('avgspeed', models.CharField(max_length=200)),
                ('score', models.CharField(max_length=200)),
                ('endpoint_lat', models.CharField(max_length=200)),
                ('endpoint_lng', models.CharField(max_length=200)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takalapp.Profile')),
            ],
        ),
    ]
