# Generated by Django 2.2.4 on 2019-08-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takalapp', '0004_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
