# Generated by Django 2.2.4 on 2019-08-13 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takalapp', '0005_profile_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='avgspeed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='burenedcalory',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='endpoint_lat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='endpoint_lng',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='passeddistance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='score',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
