# Generated by Django 2.2.4 on 2019-08-13 09:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takalapp', '0006_auto_20190813_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(default=datetime.date(2019, 8, 13)),
        ),
        migrations.AlterField(
            model_name='trip',
            name='score',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
