# Generated by Django 2.2.4 on 2019-08-14 07:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('takalapp', '0007_auto_20190813_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('store_lat', models.CharField(max_length=200)),
                ('store_lng', models.CharField(max_length=200)),
                ('score', models.IntegerField()),
                ('phone', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('score', models.CharField(max_length=200, verbose_name='امتیاز مورد نیاز')),
                ('image', models.ImageField(upload_to='images/', verbose_name='تصویر محصول')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='takalapp.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, verbose_name='تعداد')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='takalapp.Product', verbose_name='محصول')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='takalapp.Profile', verbose_name='نام کاربری')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='takalapp.Store', verbose_name='فروشگاه')),
            ],
        ),
    ]
