# Generated by Django 2.1.5 on 2019-08-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('takalapp', '0008_auto_20190814_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='store',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
